// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiyqlsbatmrwunvoihxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeXFsc2JhdG1yd3Vudm9paHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjIzOTYsImV4cCI6MjA1NzI5ODM5Nn0.PjzdfOkQpog6Ra4GMpVSZop-6DofagQsK8h8W2mnhLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);